#pragma once

/*连续模式的测试代码*/

// no error
#define EXIT_WITH_NO_ERROR 0

// file error
#define INIT_GLOBAL_CONFIG_ERROR 100
#define INIT_SHELF_CONFIG_ERROR 101
#define CORNER_FILE_IS_NOT_OPEN 102
#define POINTINFO_FILE_IS_NOT_OPEN 103

// config error
#define CONFIG_WIDTH_ERROR 200
#define CONFIG_HEIGHT_ERROR 201
#define CONFIG_DEMENSION_ERROR 202
#define CONFIG_ANGLE_ERROR 203
#define CONFIG_VALUE_TOO_BIG_ERROR 204
#define CONFIG_VALUE_TOO_SMALL_ERROR 205
#define CONFIG_SHELF_NUM_NOT_EQUAL 206

// memory error
#define H_SOLVER_IS_NULL 300
#define H_SOLVER_COOR0_IS_NULL 301
#define H_SOLVER_COOR1_IS_NULL 302
#define H_SOLVER_XY_IS_NULL 303
#define H_SOLVER_H_IS_NULL 304
#define H_SOLVER_HTRA_IS_NULL 305

// data error
#define DEMENSION_NOT_EQUAL 400
#define DEMENSION_TOO_SMALL 401
#define DEMENSION_NOT_LEGAL 402
#define VALUE_TOO_SMALL 418
#define VALUE_TOO_BIG 419
#define VALUE_NOT_LEGAL 420
#define VALUE_IS_EMPTY 421
