# General sensor definitions.
sensor_type: camera
comment: VI-Sensor cam0 (MT9M034)

# Sensor extrinsics wrt. the body-frame.
timestamp: 1305031116.2757
T_BS:
  cols: 4
  rows: 4
  data: [ 1.2456, 0.8762, 1.5139, 0.7676, 0.5307, -0.2008, -0.2981]

# Camera specific definitions.
rate_hz: 20
resolution: [640, 480]
camera_model: pinhole
intrinsics: [2301.3147, 2301.3147, 1489.8536, 479.1750] #fu, fv, cu, cv
distortion_model: radial-tangential
distortion_coefficients: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]